
server:
  port: 9000
logging:
  level:
    com.rog.EShop: DEBUG
spring:
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/e-store
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
