server:
  port: 9000
logging:
  level:
    com.rog.EShop: DEBUG
spring:
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:  ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/e-store}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resource:
        jwk:
          key-set-uri: ${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:estore}/protocol/openid-connect/certs

application:
  keycloak:
    realm: ${KEYCLOAK_REALM:estore}
    baseUrl: ${KEYCLOAK_BASE_URL:http://localhost:8080}
    clientId: ${KEYCLOAK_CLIENT_ID:estore-api}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}


