create table CATEGORIES (
                            id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
                            name varchar(255) NOT NULL ,
                            description varchar(1000) NOT NULL ,
                            PRIMARY KEY(id)
);

create table ITEMS (
                       id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
                       name varchar(255) NOT NULL ,
                       category_id int NOT NULL ,
                       short_description varchar(1000) NOT NULL,
                       full_description varchar(2000) NOT NULL ,
                       image_src varchar(500) NOT NULL ,
                       PRIMARY KEY (id),
                       CONSTRAINT ITEMS_constraint
                           FOREIGN KEY (category_id)
                               REFERENCES CATEGORIES(id)
);

insert into CATEGORIES (name, description)
values ('Комп''ютери','Комп''ютери, моноблоки'),
       ('Планшети', 'Планшети'),
       ('Монітори', 'Монітори різні модіфікації'),
       ('Клавіатури та миші','Клавіатури та миші'),
       ('Мобільні телефони', 'Мобільні телефони');

insert into ITEMS (name, category_id, short_description, full_description, image_src)
values ('Ноутбук ASUS TUF Gaming A17', '1', 'Экран 17.3" IPS (1920x1080) Full HD 144 Гц', 'Экран 17.3" IPS (1920x1080) Full HD 144 Гц, матовый / AMD Ryzen 5 4600H (3.0 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.6 кг / черный', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5bsRCubvtlvQNmiWwlFKa7A88Ysxv1dn-Z9Rk2nAfYw&s'),
       ('Ноутбук Acer Aspire 5 A515-45G-R9ML', '1', 'Экран 15.6" IPS (1920x1080) Full HD', 'Экран 15.6" IPS (1920x1080) Full HD, матовый / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 8 ГБ / SSD 512 ГБ / AMD Radeon RX 640, 2 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 1.77 кг / серебристый', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoaPv5Bvz3c5dwg4iTrTfc03DGPC6v16oFePqSn_iYvw&s'),
       ('Ноутбук Apple MacBook Air 13"', '1', 'Экран 13.3" Retina (2560x1600) WQXGA', 'Экран 13.3" Retina (2560x1600) WQXGA, глянцевый / Apple M1 / RAM 8 ГБ / SSD 256 ГБ / Apple M1 Graphics / Wi-Fi / Bluetooth / macOS Big Sur / 1.29 кг / золотой', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3u0_4uOZq7c9YRB7VWCC9fWV1EgSKcsRAjnxowWd15Q&s'),
       ('Компьютер Asus S500MC-51040F0050', '2', 'Intel Core i5-10400F (2.9 - 4.3 ГГц) / RAM 16 ГБ', 'Intel Core i5-10400F (2.9 - 4.3 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / без ОС', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyc7GV5SPxAvy-8GTx3GSH9oOvbe-qNP5Bm3jUxcma&s'),
       ('Компьютер Artline Gaming X51 v07', '2', 'Intel Core i5-10400F (2.9 - 4.3 ГГц)', 'Intel Core i5-10400F (2.9 - 4.3 ГГц) / RAM 16 ГБ / HDD 1 ТБ + SSD 240 ГБ / nVidia GeForce GTX 1660, 6 ГБ / без ОД / LAN / без ОС', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6gNKILSq0KAqKswNjNpFIex22NYm13iCd4AaVZ3n3Nw&s'),
       ('Компьютер Asus ROG Strix G15DK-R5800X1110', '2', 'AMD Ryzen 7 5800X (3.8 - 4.7 ГГц)', 'AMD Ryzen 7 5800X (3.8 - 4.7 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / без ОС', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfTpgnkQRYBMltr0zxebt67akp3Dq83qBFp7jaRRBi&s'),
       ('Планшет Lenovo Tab M10 FHD Plus', '3', 'Экран 10.3" (1920x1200) MultiTouch', 'Экран 10.3" (1920x1200) MultiTouch / MediaTek Helio P22T (2.3 ГГц) / RAM 4 ГБ / 64 ГБ встроенной памяти + microSD / Wi-Fi / Bluetooth 5.0 / основная камера 8 Мп, фронтальная - 5 Мп / Android 9.0 (Pie) / 460 г / платиновый серый', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVBMSXSbphwMoSdtsjOOTu_9SUJ84mt2iUIqoaNJL64A&s'),
       ('Планшет Huawei MatePad T10', '3', 'Экран 9.7" IPS (1280x800) MultiTouch ', 'Экран 9.7" IPS (1280x800) MultiTouch / Huawei Kirin 710A (2.2 ГГц + 1.7 ГГц) / RAM 4 ГБ / 64 ГБ встроенной памяти + MicroSD / Wi-Fi / Bluetooth 4.2 / основная камера 5 Мп, фронтальная 2 Мп / GPS / ГЛОНАСС / Android 10 (EMUI) / 450 г', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThtIxl0KzOIXGGNvrZDuTQ6pYKar4cHhC2hxirQqi41w&s'),
       ('Планшет Apple iPad 10.2"', '3', 'Экран 10.2" IPS (2160x1620) MultiTouch', 'Экран 10.2" IPS (2160x1620) MultiTouch / Apple A13 Bionic (2.65 ГГц) / 64 ГБ встроенной памяти / Wi-Fi / Bluetooth 4.2 / основная камера 8 Мп, фронтальная - 12 Мп / iPadOS 15 / 487 г / серый космос', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSjLzjoRZIFKbJJApmSX9mUknKgeNlCbF1Li64QW2AjQ&s'),
       ('Монитор 27" Dell S2722QC', '4', 'Монитор 27" Dell S2722QC (210-BBRQ) 8-Bit+FRC / USB Type-C Power Delivery 65W', 'Монитор 27" Dell S2722QC (210-BBRQ) 8-Bit+FRC / USB Type-C Power Delivery 65W', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZCZ2KNJNymS1pMFCfbQeMSuDd_xfUZuvj_wfoosEj8A&s'),
       ('Монитор 27" QUBE ', '4', 'Монитор 27" QUBE Overlord C27Q165Plus', 'Монитор 27" QUBE Overlord C27Q165Plus', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpqZDQPl3MqQTxgk7qH-RP266yOqyWH7qi5J89-wg88Q&s'),
       ('Монитор 23" Dell', '4', 'Монитор 23" Dell P2319H Black (210-APWT)', 'Монитор 23" Dell P2319H Black (210-APWT)', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8jnaIwpEO9d6P5Lvah33f47bcA-99BWxaJjCaD0_6RA&s'),
       ('Клавиатура проводная Real-El 8000 Comfort Backlit USB (EL123100033)', '5', 'Клавиатура проводная Real-El 8000 Comfort Backlit USB (EL123100033)', 'Клавиатура проводная Real-El 8000 Comfort Backlit USB (EL123100033)', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW44JqR5kAXbxZpkwxis7_Wh_GWcTGwha-6hukpJYKBg&s'),
       ('Мышь Logitech B100 USB White (910-003360)', '5', 'Мышь Logitech B100 USB White (910-003360)', 'Мышь Logitech B100 USB White (910-003360)', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz8mWaZ_IxGDPIUQSawxdnW8ZMKcHmp3A0VpI-1JvHXw&s'),
       ('Мышь HP X500', '5', 'Мышь HP X500 USB Black (E5E76AA)', 'Мышь HP X500 USB Black (E5E76AA)', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwu58D6Iv22s_z0dDwRx40zxq5-6_VbjAlwgY8Fpv0CA&s');

create table USERS (
                       id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       username varchar(50) NOT NULL UNIQUE ,
                       password varchar(256) NOT NULL ,
                       first_name varchar(50) NOT NULL ,
                       last_name varchar(50) NOT NULL ,
                       register_date timestamptz NOT NULL ,
                       account_non_expired boolean DEFAULT TRUE NOT NULL ,
                       account_non_locked boolean DEFAULT TRUE NOT NULL ,
                       credentials_non_expired boolean DEFAULT TRUE NOT NULL ,
                       enabled boolean DEFAULT TRUE NOT NULL ,
                       PRIMARY KEY (id)
);

create table USERS_ROLES (
                             user_id bigint NOT NULL ,
                             role varchar(50) NOT NULL,
                             CONSTRAINT USERS_ROLES_constraint
                                 FOREIGN KEY ( user_id)
                                     REFERENCES USERS(id)
);

insert into USERS(username, password, first_name, last_name, register_date, account_non_expired, account_non_locked, credentials_non_expired, enabled)
values('admin', 'admin', 'admin', 'admin', '2022-9-15 00:00:00 +00:00' , 'true', 'true', 'true', 'true'),
      ('user', 'user', 'user', 'user', '2022-9-15 01:00:00 +00:00', 'true', 'true', 'true', 'true');

insert into USERS_ROLES(user_id, role)
values((select id from USERS where username='admin'), 'ROLE_ADMIN'),
      ((select id from USERS where username='user'), 'ROLE_USER');

create table ROLES (
                       id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
                       name varchar(45) NOT NULL UNIQUE ,
                       PRIMARY KEY (id)
);

insert into ROLES(name)
values ('ROLE_ADMIN'),
       ('ROLE_USER');

alter table USERS_ROLES
    add column role_id bigint;

update USERS_ROLES ur set role_id=(select id from ROLES where name=ur.role);

alter table USERS_ROLES
    add CONSTRAINT ROLES_constraint
        FOREIGN KEY (role_id)
            REFERENCES ROLES(id);

alter table USERS_ROLES
drop column role;

select name, short_description, image_src from ITEMS;
select ITEMS.name,category_id, CATEGORIES.name  from ITEMS LEFT JOIN CATEGORIES on CATEGORIES.id=ITEMS.category_id;
select CATEGORIES.name, CATEGORIES.id from CATEGORIES LEFT JOIN ITEMS I on CATEGORIES.id = I.category_id;
select * from CATEGORIES LEFT JOIN ITEMS I on CATEGORIES.id = I.category_id WHERE CATEGORIES.id = 2;
select * from CATEGORIES LEFT JOIN ITEMS I on CATEGORIES.id = I.category_id where I.name = 'Монитор 27" QUBE ';
select ITEMS.name from ITEMS WHERE ITEMS.name LIKE '%L%';
select ITEMS.name from ITEMS WHERE ITEMS.name LIKE '%L%' LIMIT 2;

